### ISSUE TITLE
[s3-B] Add shipable.yml

### ISSUE THREAD

**Issue by ragsden** [aye0aye/deploy#1]
https://github.com/Shippable/pm/issues/4788

The yaml will for now have only one cluster with the name aye-aye
```````
infra:
    clusters:
        aye-aye:
            provider: ECS
            type: terraform

``````
